BMV2_SWITCH_EXE = simple_switch_grpc

include ../../utils/Makefile

# TOPO = simple-topo/topology.json
# TOPO = simple2-topo/topology.json
TOPO = simple3-topo/topology.json
# TOPO = triangle-topo/topology.json

0 log_to_elastic:
	python3 background_log_to_elastic.py